// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbaiineenkiapfsxxpzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpiYWlpbmVlbmtpYXBmc3h4cHpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwOTI3MDEsImV4cCI6MjA2NjY2ODcwMX0.3j8bTdeownrNV30aPnLxeB7wAa94WMAiLWj-Z4mhNzM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);